version: '2.1'

services:
    spring-boot-jpa-datasource:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=1q2w3e4r
        ports:
            - 5444:5432
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 10s
          timeout: 5s
          retries: 5

    spring-boot-jpa-api:
        build: .
        image: spring-boot-rest-jpa:v1.0
        ports:
            - 8082:8080
        depends_on:
          spring-boot-jpa-datasource:
            condition: service_healthy
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            #- SPRING_DATASOURCE_URL=jdbc:postgresql://docker-postgres:5432/postgres
            #- SPRING_DATASOURCE_USERNAME=postgres
            #- SPRING_DATASOURCE_PASSWORD=1q2w3e4r
            #- SPRING_DATASOURCE_GENERATE-DDL=true